### ISSUE TITLE
/users/foo/following/... endpoints don't respect the "limit" option

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-rest-api#7]
For example, open `https://api.scratch.mit.edu/users/<your username>/following/users/projects?x-token=<your token>&limit=1` (with the appropriate fields replaced). The output will be an array of 20 items.

However, setting `limit=41` causes it to error (and `limit=40` does not), which shows that it *is* still looking at the `limit` value; it's just not returning the appropriate data.

**Comment by mewtaylor** [comment]
@towerofnix anything >40 will cause an error since that's our upper limit for the limit value (I'll make sure to update the docs to include this, thanks for the reminder!). As for what you're seeing with the limit, I'm going to close the issue here, but we will be tracking it in one of our other repos!
